### ISSUE TITLE
Issue with approving commit message in interactive mode

### ISSUE THREAD

**Issue by granolocks** [gfargo/coco#1]
When using `coco -i` and then choosing 'Looks Good' to continue I get a crash like the following:

```
? Would you like to make any changes to the commit message? ✨ Looks good!                                                     
TypeError: Cannot read properties of undefined (reading 'default')
    at createCommit (/home/user/.nvm/versions/node/v18.16.1/lib/node_modules/git-coco/dist/index.js:895:55)
    at main (/home/user/.nvm/versions/node/v18.16.1/lib/node_modules/git-coco/dist/index.js:1087:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

Seems like this is failure is occurring here: https://github.com/GFargo/coco/blob/e0e7b4b500f0052c42ac8d3330e2cc0df26f3540/src/lib/utils/git/createCommit.ts#L7

Note: I had the package installed globally for this and not installed as part of the local repo.

- OS: Ubuntu 20.04
- Node Version: v18.16.1

**Comment by gfargo** [comment]
@granolocks the `createCommit` function now should use `simple-git` under the hood, hopefully, that resolves the issue 🤞 `nodegit`, while amazingly convenient, presented of a headache than it was worth.
