### ISSUE TITLE
Find an alternative to `nodegit`

### ISSUE THREAD

**Issue by gfargo** [gfargo/coco#2]
While amazingly powerful, `nodegit` provides a huge barrier to adoption by creating ridiculously long install times and external dependency on `libgit2`.

Possible alternatives:

- `simple-git` - https://github.com/steveukx/git-js
- `isomophic-git` - https://github.com/isomorphic-git/isomorphic-git

**Comment by GFargo** [comment]
This relates to #1, where the `createCommit` method would be replaced with something much simpler;

```ts
import simpleGit, { SimpleGit } from 'simple-git';

export async function createCommit(
  commitMsg: string,
  repoPath: string
): Promise<string | null> {
  const git: SimpleGit = simpleGit(repoPath);

  await git.add('.');
  await git.commit(commitMsg);

  return await git.revparse(['HEAD']);
}
```

**Comment by GFargo** [comment]
The [general adoption](https://npmtrends.com/git-client-vs-git-js-vs-isomorphic-git-vs-nodegit-vs-simple-git), along with the fact we don't need to support "in-browser" functionality is pushing me towards using `simple-git`.  

Funny thing, the original prototype of `coco` was used `simple-git` however I replaced it with `nodegit` when adopting LangChain 🤦‍♂️ ... live and learn!
