### ISSUE TITLE
.gitconfig ollama configuration error

### ISSUE THREAD

**Issue by LacazeThomas** [gfargo/coco#243]
**Describe the bug**
After a coco init with ollama selected in global project, my service section is [object Object]

**To Reproduce**

1. coco init
2. config with global scope and ollama model
3. cat ~/.gitconfig

**Expected behavior**
![Capture d’écran 2024-10-14 à 15 52 03](https://github.com/user-attachments/assets/74fc8719-75b5-4d4e-81f1-f7ed061360c6)
in my `cat ~/.gitconfig`

**Screenshots**
![Capture d’écran 2024-10-14 à 15 52 25](https://github.com/user-attachments/assets/20734926-ca6f-4fe5-83d1-d9a87d010de3)

**Desktop (please complete the following information):**

- OS: MacOS
- Shell: fish
- Version: 0.13.0

**Comment by gfargo** [comment]
Great catch 🎣 thanks for filing this issue!! this is likely related to the
new config changes that were deployed in 0.12.1

I’ll take a look at it this afternoon and see what I can do!

**Comment by gfargo** [comment]
Hey @LacazeThomas, I just released ([0.13.1](https://github.com/gfargo/coco/releases/tag/0.13.1)) which includes the fix (#244) for this issue.   Let me know if you hit any other speedbumps along the way, and thanks again for flagging this! 🙌
